import { chromium, devices } from '@playwright/test';
const b = await chromium.launch();
const ctx = await b.newContext({ ...devices['Pixel 5'] });
const page = await ctx.newPage();
let bucket = null;
page.on('response', async (r) => {
  const u = new URL(r.url());
  if (!u.pathname.startsWith('/api/measurements')) return;
  const bytes = (await r.body().catch(() => Buffer.alloc(0))).length;
  const from = u.searchParams.get('from');
  if (!bucket) bucket = { n: 0, bytes: 0, oldestFrom: from };
  bucket.n++;
  bucket.bytes += bytes;
  if (from < bucket.oldestFrom) bucket.oldestFrom = from;
});
await page.goto('http://localhost:4399/');
await page.getByText('US AQI').waitFor();
await page.waitForTimeout(8000);
const first = bucket;
bucket = null;
console.log(`load     : ${first.n} requests, ${(first.bytes / 1024).toFixed(0)} KiB, oldest from=${first.oldestFrom}`);
await page.waitForTimeout(66000);
const second = bucket;
bucket = null;
console.log(`poll +1m : ${second.n} requests, ${(second.bytes / 1024).toFixed(1)} KiB, oldest from=${second.oldestFrom}`);
await page.getByText('Trends').scrollIntoViewIfNeeded();
await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/delta-after-poll.png' });
await b.close();
